# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
