# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
