# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0003_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creator_id',
            field=models.CharField(max_length=10000),
        ),
    ]
