# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-24 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0004_auto_20181223_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_products',
            old_name='product_id',
            new_name='product_table_id',
        ),
    ]
