# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0005_auto_20181224_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
