# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeoverapp', '0007_auto_20181225_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
